spin_manifest_version = 2

[application]
name = "music"
version = "0.1.0"

[[trigger.http]]
route = "/music"
component = "music"

[[trigger.http]]
route = "/mul"
component = "music"


[component.music]
description = "My music app"
source = "httphandler_composed.wasm"
