apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageclassify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageclassify
  template:
    metadata:
      labels:
        app: imageclassify
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
        - name: imageclassify
          image: ghcr.io/petersalomonsen/imageclassify:0.0.1
          command: ["/"]
---
apiVersion: v1
kind: Service
metadata:
  name: imageclassify
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: imageclassify
---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: imageclassify
spec:
    hosts:
    - myhost.com
    pathPrefixes:
    - /
    scaleTargetRef:
        name: imageclassify
        kind: Deployment
        apiVersion: apps/v1
        service: imageclassify
        port: 80
    scaledownPeriod: 5
    replicas:
        min: 0
        max: 1
      