// Generated by `wit-bindgen` 0.21.0. DO NOT EDIT!
// Options used:
pub mod example {
  pub mod tonegenerator {
    #[allow(clippy::all)]
    pub mod tonegeneratorsynth {
      #[used]
      #[doc(hidden)]
      #[cfg(target_arch = "wasm32")]
      static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      pub fn setnote(notenumber: f32,){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "example:tonegenerator/tonegeneratorsynth")]
          extern "C" {
            #[link_name = "setnote"]
            fn wit_import(_: f32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          fn wit_import(_: f32, ){ unreachable!() }
          wit_import(_rt::as_f32(&notenumber));
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      pub fn nextsample() -> f32{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "example:tonegenerator/tonegeneratorsynth")]
          extern "C" {
            #[link_name = "nextsample"]
            fn wit_import() -> f32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          fn wit_import() -> f32{ unreachable!() }
          let ret = wit_import();
          ret
        }
      }

    }

  }
}
mod _rt {

  pub fn as_f32<T: AsF32>(t: T) -> f32 {
    t.as_f32()
  }

  pub trait AsF32 {
    fn as_f32(self) -> f32;
  }

  impl<'a, T: Copy + AsF32> AsF32 for &'a T {
    fn as_f32(self) -> f32 {
      (*self).as_f32()
    }
  }
  
  impl AsF32 for f32 {
    #[inline]
    fn as_f32(self) -> f32 {
      self as f32
    }
  }
}

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.21.0:tonegeneratorimports:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 289] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x96\x01\x01A\x02\x01\
A\x02\x01B\x04\x01@\x01\x0anotenumberv\x01\0\x04\0\x07setnote\x01\0\x01@\0\0v\x04\
\0\x0anextsample\x01\x01\x03\x01(example:tonegenerator/tonegeneratorsynth\x05\0\x04\
\x01*example:tonegenerator/tonegeneratorimports\x04\0\x0b\x1a\x01\0\x14tonegener\
atorimports\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.201.0\x10wit-bindgen-rust\x060.21.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

