/* Automatically generated by wasm2c */
#ifndef INSTRUMENTS_H_GENERATED_
#define INSTRUMENTS_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_environment;
extern f32* w2c_environment_SAMPLERATE(struct w2c_environment*);

typedef struct w2c_instruments {
  /* import: 'environment' 'SAMPLERATE' */
  f32 *w2c_environment_SAMPLERATE;
  f32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_g4;
  f64 w2c_g5;
  u32 w2c_g6;
  u32 w2c_g7;
  u32 w2c_g8;
  u32 w2c_g9;
  u32 w2c_g10;
  u32 w2c_samplebuffer;
  u32 w2c_g12;
  u32 w2c_g13;
  u32 w2c_g14;
  u32 w2c_g15;
  u32 w2c_g16;
  f64 w2c_g17;
  u32 w2c_g18;
  u32 w2c_g19;
  u32 w2c_g20;
  f64 w2c_g21;
  f64 w2c_currentTimeMillis;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_instruments;

void wasm2c_instruments_instantiate(w2c_instruments*, struct w2c_environment*);
void wasm2c_instruments_free(w2c_instruments*);
wasm_rt_func_type_t wasm2c_instruments_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'getDuration' */
u32 w2c_instruments_getDuration(w2c_instruments*);

/* export: 'fillSampleBuffer' */
void w2c_instruments_fillSampleBuffer(w2c_instruments*);

/* export: 'fillSampleBufferWithNumSamples' */
void w2c_instruments_fillSampleBufferWithNumSamples(w2c_instruments*, u32);

/* export: 'samplebuffer' */
u32* w2c_instruments_samplebuffer(w2c_instruments* instance);

/* export: 'allNotesOff' */
void w2c_instruments_allNotesOff(w2c_instruments*);

/* export: 'shortmessage' */
void w2c_instruments_shortmessage(w2c_instruments*, u32, u32, u32);

/* export: 'getActiveVoicesStatusSnapshot' */
u32 w2c_instruments_getActiveVoicesStatusSnapshot(w2c_instruments*);

/* export: 'seek' */
void w2c_instruments_seek(w2c_instruments*, u32);

/* export: 'playEventsAndFillSampleBuffer' */
void w2c_instruments_playEventsAndFillSampleBuffer(w2c_instruments*);

/* export: 'currentTimeMillis' */
f64* w2c_instruments_currentTimeMillis(w2c_instruments* instance);

/* export: 'memory' */
wasm_rt_memory_t* w2c_instruments_memory(w2c_instruments* instance);

#ifdef __cplusplus
}
#endif

#endif  /* INSTRUMENTS_H_GENERATED_ */
